defaults:
  - ./trace_grpo-sudoku6x6-4n8g-megatron-vllm-async-long.yaml
  - ../../../block_diffusion/configs/validation/ar_diffusion.yaml
logger:
  log_dir: results/trace_grpo_sudoku6x6_vllm_async_dualval
  wandb:
    name: ${oc.env:WANDB_RUN_NAME,trace_grpo_sudoku6x6_vllm_async_dualval}
